"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RESPONSE = void 0;
exports.RESPONSE = `
[
    {
        "Line": "Antelope Valley Line",
        "LineAbbreviation": "AV",
        "ServiceAdvisories": [
            {
                "Id": 9945,
                "Message": "AV Line 203 to Vista Canyon will use track 2 at Glendale today.",
                "Line": "AV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733528227000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 7:37 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9945",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 9936,
                "Message": "Good morning! We\u0027ll be posting your train status updates from 4:00 a.m. to 12:30 a.m. Be safe and have a great day!",
                "Line": "AV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733515300000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 4:01 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9936",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 1192002,
                "Message": "Planned Advisory for Winter Holidays",
                "Line": "AV",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1732119792573)\/",
                "StartDateTime": "\/Date(1735135200000)\/",
                "ShortStartDateTime": "12/25/2024",
                "EndDateTime": "\/Date(1735801200000)\/",
                "ShortEndDateTime": "1/1/2025",
                "Timestamp": "11/20/2024 12:23 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1192002",
                "AlertDetailsPage": null,
                "DateRangeOutput": "12/25/2024 - 1/1/2025"
            }
        ]
    },
    {
        "Line": "Inland Empire-Orange County Line",
        "LineAbbreviation": "IEOC",
        "ServiceAdvisories": [
            {
                "Id": 9937,
                "Message": "Good morning! We\u0027ll be posting your train status updates from 4:00 a.m. to 12:30 a.m. Be safe and have a great day!",
                "Line": "IEOC",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733515301000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 4:01 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9937",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 1192002,
                "Message": "Planned Advisory for Winter Holidays",
                "Line": "IEOC",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1732119792573)\/",
                "StartDateTime": "\/Date(1735135200000)\/",
                "ShortStartDateTime": "12/25/2024",
                "EndDateTime": "\/Date(1735801200000)\/",
                "ShortEndDateTime": "1/1/2025",
                "Timestamp": "11/20/2024 12:23 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1192002",
                "AlertDetailsPage": null,
                "DateRangeOutput": "12/25/2024 - 1/1/2025"
            }
        ]
    },
    {
        "Line": "Orange County Line",
        "LineAbbreviation": "OC",
        "ServiceAdvisories": [
            {
                "Id": 9938,
                "Message": "Good morning! We\u0027ll be posting your train status updates from 4:00 a.m. to 12:30 a.m. Be safe and have a great day!",
                "Line": "OC",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733515297000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 4:01 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9938",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 1192002,
                "Message": "Planned Advisory for Winter Holidays",
                "Line": "OC",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1732119792573)\/",
                "StartDateTime": "\/Date(1735135200000)\/",
                "ShortStartDateTime": "12/25/2024",
                "EndDateTime": "\/Date(1735801200000)\/",
                "ShortEndDateTime": "1/1/2025",
                "Timestamp": "11/20/2024 12:23 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1192002",
                "AlertDetailsPage": null,
                "DateRangeOutput": "12/25/2024 - 1/1/2025"
            }
        ]
    },
    {
        "Line": "Riverside Line",
        "LineAbbreviation": "RIV",
        "ServiceAdvisories": [
            {
                "Id": 9944,
                "Message": "RIV Line 403 to Los Angeles is delayed 15 to 20 minutes due to freight congestion.",
                "Line": "RIV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733523639000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 6:20 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9944",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 9939,
                "Message": "Good morning! We\u0027ll be posting your train status updates from 4:00 a.m. to 12:30 a.m. Be safe and have a great day!",
                "Line": "RIV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733515297000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 4:01 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9939",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 1192002,
                "Message": "Planned Advisory for Winter Holidays",
                "Line": "RIV",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1732119792573)\/",
                "StartDateTime": "\/Date(1735135200000)\/",
                "ShortStartDateTime": "12/25/2024",
                "EndDateTime": "\/Date(1735801200000)\/",
                "ShortEndDateTime": "1/1/2025",
                "Timestamp": "11/20/2024 12:23 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1192002",
                "AlertDetailsPage": null,
                "DateRangeOutput": "12/25/2024 - 1/1/2025"
            }
        ]
    },
    {
        "Line": "San Bernardino Line",
        "LineAbbreviation": "SB",
        "ServiceAdvisories": [
            {
                "Id": 9949,
                "Message": "San Bernardino Line trains 314, 322, 330, 327, 335 and 343 are suspended indefinitely. This schedule adjustment is being made to improve on-time service for the other 48 SB Line trains each weekday. For more information call or text (800) 371-5465. https://t.co/7czjfYNt5F",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733533243000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 9:00 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9949",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 9947,
                "Message": "SB Line 315 to Los Angeles is delayed 15 minutes due to train congestion.",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733532674000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 8:51 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9947",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 9948,
                "Message": "SB Line 304 to San Bernardino Downtown is delayed 10 minutes due to speed restrictions.",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733532647000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 8:50 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9948",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 9942,
                "Message": "SB Line Alert: Effective now through December 31, the Sante Fe Rd. entrance at Pomona-North will be closed to all through traffic. Instead, use the Fulton Rd. entrance for travel, parking, and ticket machine use. Pedestrian access will be open from both entrances. https://t.co/AgGYHAxZjY",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733517013000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 4:30 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9942",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 9940,
                "Message": "Good morning! We\u0027ll be posting your train status updates from 4:00 a.m. to 12:30 a.m. Be safe and have a great day!",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733515301000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 4:01 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9940",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 1192002,
                "Message": "Planned Advisory for Winter Holidays",
                "Line": "SB",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1732119792573)\/",
                "StartDateTime": "\/Date(1735135200000)\/",
                "ShortStartDateTime": "12/25/2024",
                "EndDateTime": "\/Date(1735801200000)\/",
                "ShortEndDateTime": "1/1/2025",
                "Timestamp": "11/20/2024 12:23 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1192002",
                "AlertDetailsPage": null,
                "DateRangeOutput": "12/25/2024 - 1/1/2025"
            },
            {
                "Id": 1190913,
                "Message": "Planned Advisory for Arrow Service ",
                "Line": "SB",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1730760652970)\/",
                "StartDateTime": "\/Date(1730760600000)\/",
                "ShortStartDateTime": "11/4/2024",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "11/4/2024 6:50 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1190913",
                "AlertDetailsPage": null,
                "DateRangeOutput": "11/4/2024 until further notice."
            }
        ]
    },
    {
        "Line": "Ventura County Line",
        "LineAbbreviation": "VC",
        "ServiceAdvisories": [
            {
                "Id": 9946,
                "Message": "VC Line 107 to Moorpark will use track 2 at Glendale today.",
                "Line": "VC",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733531387000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 8:29 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9946",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 9941,
                "Message": "Good morning! We\u0027ll be posting your train status updates from 4:00 a.m. to 12:30 a.m. Be safe and have a great day!",
                "Line": "VC",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733515299000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 4:01 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9941",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 1192002,
                "Message": "Planned Advisory for Winter Holidays",
                "Line": "VC",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1732119792573)\/",
                "StartDateTime": "\/Date(1735135200000)\/",
                "ShortStartDateTime": "12/25/2024",
                "EndDateTime": "\/Date(1735801200000)\/",
                "ShortEndDateTime": "1/1/2025",
                "Timestamp": "11/20/2024 12:23 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1192002",
                "AlertDetailsPage": null,
                "DateRangeOutput": "12/25/2024 - 1/1/2025"
            }
        ]
    },
    {
        "Line": "91/Perris Valley Line",
        "LineAbbreviation": "91/PV",
        "ServiceAdvisories": [
            {
                "Id": 9943,
                "Message": "91/PV Line Alert: Effective December 10 through December 20, the Case Road entrance east of Mapes Road will be closed to traffic due to construction. During this time, please use Murrieta Road or Ethanac Road for access.",
                "Line": "91/PV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733518877000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 5:01 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9943",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 9935,
                "Message": "Good morning! We\u0027ll be posting your train status updates from 4:00 a.m. to 12:30 a.m. Be safe and have a great day!",
                "Line": "91/PV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1733515298000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "12/6/2024 4:01 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=9935",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 1192002,
                "Message": "Planned Advisory for Winter Holidays",
                "Line": "91/PV",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1732119792573)\/",
                "StartDateTime": "\/Date(1735135200000)\/",
                "ShortStartDateTime": "12/25/2024",
                "EndDateTime": "\/Date(1735801200000)\/",
                "ShortEndDateTime": "1/1/2025",
                "Timestamp": "11/20/2024 12:23 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1192002",
                "AlertDetailsPage": null,
                "DateRangeOutput": "12/25/2024 - 1/1/2025"
            }
        ]
    }
]
`;
