export const RESPONSE = `
[
    {
        "Line": "Antelope Valley Line",
        "LineAbbreviation": "AV",
        "ServiceAdvisories": [
            {
                "Id": 14311,
                "Message": "AV Line 207 to Lancaster will use track 1 at Vista Canyon today (10:52 am departure).",
                "Line": "AV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744762752000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 10:19 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14311",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14309,
                "Message": "AV Line 207 to Lancaster will use track 4A at Union Station today (9:39 am departure).",
                "Line": "AV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744759114000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 9:18 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14309",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14307,
                "Message": "AV Line 204 to Los Angeles is delayed 10 to 15 minutes due to a mechanical issue.",
                "Line": "AV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744754514000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 8:01 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14307",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14304,
                "Message": "AV Line 201 to Lancaster will use track 1 at Vista Canyon today (7:52 am departure).",
                "Line": "AV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744751530000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 7:12 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14304",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            }
        ]
    },
    {
        "Line": "Inland Empire-Orange County Line",
        "LineAbbreviation": "IEOC",
        "ServiceAdvisories": [
            {
                "Id": 1200988,
                "Message": "Planned Advisory for the 91/Perris Valley and Inland Empire-Orange County lines",
                "Line": "IEOC",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1744739962953)\/",
                "StartDateTime": "\/Date(1745672400000)\/",
                "ShortStartDateTime": "4/26/2025",
                "EndDateTime": "\/Date(1745730000000)\/",
                "ShortEndDateTime": "4/26/2025",
                "Timestamp": "4/15/2025 3:59 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1200988",
                "AlertDetailsPage": null,
                "DateRangeOutput": "4/26/2025 - 4/26/2025"
            }
        ]
    },
    {
        "Line": "Orange County Line",
        "LineAbbreviation": "OC",
        "ServiceAdvisories": [
            {
                "Id": 14312,
                "Message": "OC Line 612 to Laguna Niguel/Mission Viejo will use track 11B at Union Station today (10:40 am departure).",
                "Line": "OC",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744762605000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 10:16 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14312",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            }
        ]
    },
    {
        "Line": "Riverside Line",
        "LineAbbreviation": "RIV",
        "ServiceAdvisories": [
            {
                "Id": 14317,
                "Message": "RV Line 412  to Riverside Downtown will use track 10B at LA Union Station.",
                "Line": "RIV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744777542000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 2:25 PM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14317",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14316,
                "Message": "RIV Line 419 to LA Union Station will use track 2 at Ontario-East.",
                "Line": "RIV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744773626000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 1:20 PM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14316",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14303,
                "Message": "RIV Line 405 to Los Angeles will use track 2 at Montebello/Commerce today (7:04 am departure).",
                "Line": "RIV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744750461000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 6:54 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14303",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            }
        ]
    },
    {
        "Line": "San Bernardino Line",
        "LineAbbreviation": "SB",
        "ServiceAdvisories": [
            {
                "Id": 14321,
                "Message": "Sat. \u0026 Sun. April 26 \u0026 27, San Bernardino Line trains will not operate. This is due to track projects to ensure rail safety. Alternate transportation is not available. Arrow trains will run on their regular weekend schedule. Visit https://t.co/HO0YcC7QDR or call 800-371-5465 https://t.co/uKrPXFrwXf",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744780214000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 3:10 PM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14321",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14318,
                "Message": "SB  Line 342 to San Bernadino Downtown will use track 8B at LA Union Station.",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744777468000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 2:24 PM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14318",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14319,
                "Message": "SB  Line 340 to San Bernadino Downtown will use track 8A at LA Union Station.",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744777433000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 2:23 PM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14319",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14310,
                "Message": "SB Line 316 to San Bernardino-Downtown will use track 7B Union Station today (10:40 am departure).",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744761388000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 9:56 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14310",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14308,
                "Message": "SB Line Alert Update: Power has been restored at San Bernadino Depot.",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744757392000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 8:49 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14308",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14306,
                "Message": "SB Line 317 to Los Angeles will use track 2 at Rancho Cucamonga today (8:13 am departure).",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744754023000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 7:53 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14306",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14305,
                "Message": "SB Line Alert: San Bernadino Depot is experiencing a temporary power outage. This may impact station signage, elevators and ticket vending machines. Updates to follow.",
                "Line": "SB",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744751179000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 7:06 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14305",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 1200329,
                "Message": "Planned Advisory for the San Bernardino and Arrow Lines  ",
                "Line": "SB",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1743728287740)\/",
                "StartDateTime": "\/Date(1745650800000)\/",
                "ShortStartDateTime": "4/26/2025",
                "EndDateTime": "\/Date(1745823540000)\/",
                "ShortEndDateTime": "4/27/2025",
                "Timestamp": "4/3/2025 10:58 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1200329",
                "AlertDetailsPage": null,
                "DateRangeOutput": "4/26/2025 - 4/27/2025"
            },
            {
                "Id": 1200980,
                "Message": "Planned Advisory for Arrow service",
                "Line": "SB",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1744736640120)\/",
                "StartDateTime": "\/Date(1745229600000)\/",
                "ShortStartDateTime": "4/21/2025",
                "EndDateTime": "\/Date(1745650740000)\/",
                "ShortEndDateTime": "4/25/2025",
                "Timestamp": "4/15/2025 3:04 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1200980",
                "AlertDetailsPage": null,
                "DateRangeOutput": "4/21/2025 - 4/25/2025"
            }
        ]
    },
    {
        "Line": "Ventura County Line",
        "LineAbbreviation": "VC",
        "ServiceAdvisories": [
            {
                "Id": 14315,
                "Message": "VC Line 115 to Ventura-East will use track 2 at Chatsworth today.",
                "Line": "VC",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744766004000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 11:13 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14315",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14314,
                "Message": "Update: VC Line 115 to Ventura-East is on the move, delayed 20 to 25 minutes due to an unruly passenger.",
                "Line": "VC",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744764838000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 10:53 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14314",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14313,
                "Message": "VC Line 115 to Ventura-East is holding at Union Station due to an unruly passenger. Delays are unknown, updates to follow.",
                "Line": "VC",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744763560000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 10:32 AM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14313",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            }
        ]
    },
    {
        "Line": "91/Perris Valley Line",
        "LineAbbreviation": "91/PV",
        "ServiceAdvisories": [
            {
                "Id": 14322,
                "Message": "91/PV Line 719 to Los Angeles is stopped at Buena Park due to BNSF PTC system issues. Updates to follow.",
                "Line": "91/PV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744780475000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 3:14 PM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14322",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 14320,
                "Message": "ML 736 to Perris-South will use track 11B at LA Union Station.",
                "Line": "91/PV",
                "Platform": "",
                "PlayTime": "",
                "CreateDate": "\/Date(1744777330000)\/",
                "StartDateTime": "\/Date(-62135568000000)\/",
                "ShortStartDateTime": "1/1/0001",
                "EndDateTime": null,
                "ShortEndDateTime": null,
                "Timestamp": "4/15/2025 2:22 PM",
                "Type": "Service Advisory",
                "DetailsPage": "?alertId=14320",
                "AlertDetailsPage": null,
                "DateRangeOutput": "1/1/0001 until further notice."
            },
            {
                "Id": 1200988,
                "Message": "Planned Advisory for the 91/Perris Valley and Inland Empire-Orange County lines",
                "Line": "91/PV",
                "Platform": "",
                "PlayTime": null,
                "CreateDate": "\/Date(1744739962953)\/",
                "StartDateTime": "\/Date(1745672400000)\/",
                "ShortStartDateTime": "4/26/2025",
                "EndDateTime": "\/Date(1745730000000)\/",
                "ShortEndDateTime": "4/26/2025",
                "Timestamp": "4/15/2025 3:59 AM",
                "Type": "Planned Advisory",
                "DetailsPage": "?alertId=1200988",
                "AlertDetailsPage": null,
                "DateRangeOutput": "4/26/2025 - 4/26/2025"
            }
        ]
    }
]
`